---
apiVersion: v1
kind: Pod
metadata:
  name: my-vol-sample
  labels:
    app: mysql
spec:
  containers:
    - image: mysql:8-debian
      name: my-vol-pod
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: nop
        - name: MYSQL_USER
          value: gopivurata
        - name: MYSQL_PASSWORD
          value: gopivurata
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql
  volumes:
    - persistentVolumeClaim:
        claimName: my-nop-pvc
        readOnly: false
      name: mysql
        