---
apiVersion: v1
kind: Service
metadata:
  name: my-mysql-svc
spec:
  type: ExternalName
  externalName: mysql.nop.com
  selector:
    app: mysql
  ports:
    - port: 31500
      targetPort: 3306
      protocol: TCP